### PR TITLE
two-way databinding kotlin

### PR DESCRIPTION
**Pull request by OyaCanli**
added warning for unsaved changes, changed data class, check for empty toy

### CODE REVIEW

**Review by rajtheinnovator — APPROVED** [review]
@OyaCanli the code runs fine and I can see also the unsaved changes warning properly. We can merge it and next we can now focus on the article parts. Looks like we've covered the code and so will soon be ready to marge all branches to master. 

Later on, as per feedback from the community, we can correct code/article as and when needed after it's released.

**Comment by OyaCanli** [comment]
@rajtheinnovator That's good! Thanks for reviewing. 
I also wanted to use some extension functions for simple repetitive tasks (like toasts, snack, fragment transaction) as it is common in kotlin world. However I wanted to agree together what to use. I think best option is android ktx library but I think it is available only for androidx. Otherwise there is Anko which provides extensions for toast, snack, alertdialog etc.. But I didn't see fragment transaction. And a third option could be to have our own extension functions in a file in the project.

**Comment by rajtheinnovator** [comment]
@OyaCanli I know, this is lot of hard work already, but maybe you'd like to create an advanced sample including all the complex or easy concepts, to help serve a complete repo. Not now exactly, I'll share more ideas on it once we've first published it or nearing publishing. Great work so far :clap:  :raised_hands:

**Comment by OyaCanli** [comment]
@rajtheinnovator Frankly, I think it is enough. But I want to return working on a project of mine, which use databinding exhaustively. When it will be ready, we can show it as a more complex example as well, if you wish.. 
By the way, don't forget that there is still kotlin version of the sample with NewsApi.

**Comment by rajtheinnovator** [comment]
I though we could keep everything on databinding in same repo but yes, you're absolutely right, the more detailed uses can be put in use, in those other samples we have. Let's go with the strategy you suggested here @OyaCanli :+1:

**Pull request merged**
