### PR TITLE
Revert "Dev databinding newsapi kotlin"

### PR DESCRIPTION
**Pull request by rajtheinnovator**
Reverts enpassio/Databinding#43

### CODE REVIEW

**Comment by OyaCanli** [comment]
@rajtheinnovator I tried reverted branch, it seems good to me.

**Comment by rajtheinnovator** [comment]
@OyaCanli I'll check all the samples from test1 branch and if they all look good, which should be now, I'll merge them into master. You can now prepare the complete articles 👍

**Comment by rajtheinnovator** [comment]
@OyaCanli I had tested all the branches on my device and they all run as expected. So I've merged everything to master. You can keep working on the articles. And I must say, I've recently been to a meetup on android by Google where there was a detailed session on Databinding but I could still see lots of voids there. The work you've done is impressive and it feels to fill a lot of that void. This is surely going to be a very helpful resource for everyone out there :+1:

**Comment by OyaCanli** [comment]
@rajtheinnovator Thanks! That's nice to hear. 
I am working on the article. I prepared gists and I have changed observable fields part due to the latest recommendations on using livedata instead. But I didn't remove that part. I thought of using livedata in newsapi(as I already did) and observable fields in two-way, for demonstrating both. As I write I feel need to add some things to samples, to demonstrate what I write in the article. So I can still make some small changes.

**Comment by rajtheinnovator** [comment]
Yeah, sure thing @OyaCanli . We can create a new PR whenever you make new changes to keep the code updated :+1:

**Pull request merged**
