### PR TITLE
databinding newsapi java

### PR DESCRIPTION
**Pull request by OyaCanli**
The sample is mostly done. I consider a few changes/additions but I want to send this like this, so that you can see what we have up to here and we can discuss on further points.

### CODE REVIEW

**Comment by rajtheinnovator** [comment]
Looks good to me, @OyaCanli . I'll be merging the PR now and then by the next evening, I'll be checking both Java and Kotlin version to see if there is any sync required, though I think it's going perfectly. Thanks a lot for working on this continuously. And now, may I request you that please try writing the article to be published on Medium? Maybe both of you and Greta can collaborate again to do that part. As this is holidays so I hope you enjoy that and do this part after you get some time. Hoping to see first article published on Enpassio soon. Thanks again and stay Enpassious :D I'm also trying to do architecture parts and should be able to get some solid progress on that very soon.

**Comment by OyaCanli** [comment]
Thanks! There is something I consider changing. But I want to ask your ideas:
-I have put the network checking logic in the ArticleListFragment: https://github.com/enpassio/Databinding/blob/dev-databinding-newsapi/DatabindingWithNewsApi/app/src/main/java/com/enpassio/databindingwithnewsapi/ui/ArticleListFragment.java
If you don't have connection it shows a snack with a button to retry which checks again etc..  
On the other hand, if you have the connection and get the news, go to details, then cut internet and come back to list, it checks the connection again and show no network warning. In the news app we have done in ABND that was the expected behaviour. But since we're using a repository here, we still have the data we fetched. So it shows no network warning(and an empty list) although the data is already in our repository. So I consider changing it. May be by moving the network checking logic to repository ( but it will require to pass a context and probably a callback to inform ui) Or I can change the point where we start fetching data, move it away from the constructor, so ArticleListFragment can subscribe to ViewModel even if there is no network.. I'll experiment with this.. 
But what do you think is the correct behaviour? @rajtheinnovator @GretaGri

**Comment by rajtheinnovator** [comment]
@OyaCanli the idea behavior is that, the UI should care only of the contents to be shown on the screen and so the network checking part could be moved from here. The best place obviously would be either repository(it can be given the task to check for network but will do so only in separate class) or utils(better this).

**Comment by OyaCanli** [comment]
Ok, thanks @rajtheinnovator . I'll try like that then. 

I'm less enthousiastic for the writing part, but I know, we should do that part as well. 

As a reminder: For kotlin repo(recyclerview), don't merge it yet. There is a problem with package name. @GretaGri said she will fix it when she has time.

**Comment by rajtheinnovator** [comment]
@OyaCanli  the first PR was merged but yes, I'll wait for that to be fixed before making the final merge with master. I can understand that part about writing but hopefully that'll also be helpful for the community  and all of us :smile: as well

**Pull request merged**
